'use client';
import { useState } from 'react';
import { useConnection, useWalletClient } from 'wagmi';
import { useQueryClient } from '@tanstack/react-query';
import { formatEther, type Address } from 'viem';
import { Coins, Check, ShieldCheck, Lock, ArrowUpRight, AlertCircle, RefreshCw } from 'lucide-react';
import { routerTransaction } from '@/lib/forge/router';
import { chain, explorer } from '@/lib/config';
import { WalletButton } from './wallet';

function formatEthValue(wei: bigint | string | number): string {
  try {
    const val = typeof wei === 'number' ? wei : Number(formatEther(BigInt(wei)));
    if (val === 0) return '0';
    if (val >= 1000) {
      return val.toLocaleString('en-US', { maximumFractionDigits: 2 });
    }
    if (val >= 1) {
      return val.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 4 });
    }
    if (val >= 0.0001) {
      return val.toLocaleString('en-US', { maximumFractionDigits: 4 });
    }
    return '<0.0001';
  } catch {
    return '0';
  }
}

export function CreatorFeePanel({
  routerAddress,
  creatorAddress,
  tokenAddress,
  claimable,
  totalReceived,
  totalProcessed,
  destinations,
  isLoading = false,
}: {
  routerAddress?: Address;
  creatorAddress?: Address;
  tokenAddress: Address;
  claimable: bigint | null;
  totalReceived: bigint;
  totalProcessed: bigint;
  destinations?: readonly { recipient: Address; bps: number; kind: number }[];
  isLoading?: boolean;
}) {
  const { address } = useConnection();
  const { data: wallet } = useWalletClient();
  const queryClient = useQueryClient();

  const [modalOpen, setModalOpen] = useState(false);
  const [txState, setTxState] = useState<
    'idle' | 'awaiting signature' | 'confirming' | 'confirmed' | 'failed'
  >('idle');
  const [txHash, setTxHash] = useState<string>('');
  const [errorMsg, setErrorMsg] = useState<string>('');

  // Check if connected wallet is the creator or an eligible fee recipient
  const isConnected = !!address;
  const isEligibleCreator =
    isConnected &&
    ((creatorAddress && address.toLowerCase() === creatorAddress.toLowerCase()) ||
      (destinations &&
        destinations.some(
          (d) => d.recipient.toLowerCase() === address.toLowerCase(),
        )) ||
      (claimable !== null && claimable > 0n));

  const claimableEth = claimable !== null ? Number(formatEther(claimable)) : 0;
  const hasClaimable = claimable !== null && claimable > 0n;

  async function executeClaim() {
    if (!wallet || !address || !routerAddress) return;
    setTxState('awaiting signature');
    setErrorMsg('');
    try {
      await routerTransaction(
        wallet,
        address,
        routerAddress,
        'claim',
        (hash) => {
          setTxHash(hash);
          setTxState('confirming');
        },
      );
      setTxState('confirmed');
      await queryClient.invalidateQueries({ queryKey: ['token-router', tokenAddress] });
      await queryClient.invalidateQueries({ queryKey: ['token-market', tokenAddress] });
    } catch (err) {
      setTxState('failed');
      setErrorMsg((err as Error).message);
    }
  }

  return (
    <div className="creator-fees-terminal-card" aria-busy={isLoading}>
      <div className="creator-card-header">
        <div className="creator-title-block">
          <div className="section-eyebrow">
            <span className="lime-dot" />
            <span>CREATOR FEES</span>
          </div>
          <h3 className="creator-heading">CREATOR REVENUE</h3>
        </div>

        {isLoading ? (
          <span className="skeleton skeleton-status" />
        ) : isEligibleCreator ? (
          <span className="creator-verified-badge">
            <ShieldCheck size={14} /> RECOGNIZED CREATOR
          </span>
        ) : (
          <span className="public-view-badge">
            <Lock size={13} /> PUBLIC VIEW
          </span>
        )}
      </div>

      <div className="creator-stats-grid">
        <div className="creator-stat-box highlight-box">
          <span className="creator-stat-label">CLAIMABLE</span>
          <strong className="creator-stat-val font-mono">
            {isConnected ? formatEthValue(claimableEth) : '—'}
            <small className="creator-unit">ETH</small>
          </strong>
          <span className="creator-stat-sub">
            {isConnected
              ? hasClaimable
                ? 'Ready to withdraw immediately'
                : 'No uncollected fees at this moment'
              : 'Connect wallet to inspect balance'}
          </span>
        </div>

        <div className="creator-stat-box">
          <span className="creator-stat-label">LIFETIME</span>
          <strong className="creator-stat-val font-mono">
            {formatEthValue(totalReceived)}
            <small className="creator-unit">ETH</small>
          </strong>
          <span className="creator-stat-sub">Fees generated by token trading</span>
        </div>

        <div className="creator-stat-box">
          <span className="creator-stat-label">PROCESSED</span>
          <strong className="creator-stat-val font-mono">
            {formatEthValue(totalProcessed)}
            <small className="creator-unit">ETH</small>
          </strong>
          <span className="creator-stat-sub">Sent through the current flow</span>
        </div>
      </div>

      {/* ACTION AREA */}
      <div className="creator-action-bar">
        {!isConnected ? (
          <div className="creator-connect-wrap">
            <p className="muted text-sm">
              CONNECT TO VIEW YOUR SHARE
            </p>
            <WalletButton />
          </div>
        ) : isEligibleCreator ? (
          <div className="creator-claim-action-row">
            <button
              type="button"
              className="button button-lime"
              disabled={!hasClaimable || txState === 'confirming'}
              onClick={() => {
                setTxState('idle');
                setModalOpen(true);
              }}
            >
              <Coins size={16} />
              <span>{hasClaimable ? `CLAIM ${claimableEth.toFixed(4)} ETH` : 'NOTHING TO CLAIM'}</span>
            </button>
            <span className="creator-auth-note text-xs muted font-mono">
              Dedicated router: {routerAddress?.slice(0, 6)}…{routerAddress?.slice(-4)}
            </span>
          </div>
        ) : (
          <div className="public-notice-banner">
            <Lock size={15} className="muted" />
            <span className="text-xs muted">
              PUBLIC VIEW
            </span>
          </div>
        )}
      </div>

      {/* TRANSACTION MODAL */}
      {modalOpen && (
        <div className="event-detail-modal-overlay" onClick={() => setModalOpen(false)}>
          <div className="event-detail-modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header-row">
              <span className="event-modal-badge bg-lime-400 text-black">CREATOR CLAIM</span>
              <button
                type="button"
                className="modal-close-btn"
                onClick={() => setModalOpen(false)}
              >
                ✕
              </button>
            </div>

            <h3 className="event-modal-title">CLAIM CREATOR FEES</h3>
            <p className="event-modal-desc">
              Execute on-chain withdrawal from the dedicated ForgeRouter to your connected wallet.
            </p>

            <dl className="event-modal-dl font-mono text-xs">
              <div className="dl-row">
                <dt>AMOUNT</dt>
                <dd className="font-bold text-lime-600">{claimableEth.toFixed(6)} ETH</dd>
              </div>
              <div className="dl-row">
                <dt>FROM ROUTER</dt>
                <dd>{routerAddress ? `${routerAddress.slice(0, 6)}…${routerAddress.slice(-4)}` : '—'}</dd>
              </div>
              <div className="dl-row">
                <dt>TO WALLET</dt>
                <dd>{address ? `${address.slice(0, 6)}…${address.slice(-4)}` : '—'}</dd>
              </div>
              <div className="dl-row">
                <dt>NETWORK</dt>
                <dd>{chain.name}</dd>
              </div>
            </dl>

            {txState === 'idle' && (
              <button
                type="button"
                className="button button-lime full mt-4"
                onClick={executeClaim}
              >
                <span>CONFIRM CLAIM</span>
                <ArrowUpRight size={16} />
              </button>
            )}

            {txState === 'awaiting signature' && (
              <div className="tx-status-card mt-4">
                <RefreshCw size={20} className="animate-spin text-lime-600" />
                <span>Confirm signature in wallet…</span>
              </div>
            )}

            {txState === 'confirming' && (
              <div className="tx-status-card mt-4">
                <RefreshCw size={20} className="animate-spin text-lime-600" />
                <span>Transaction confirming on Robinhood Chain…</span>
              </div>
            )}

            {txState === 'confirmed' && (
              <div className="tx-success-card mt-4">
                <Check size={24} className="text-lime-600" />
                <strong>FEES CLAIMED SUCCESSFULLY</strong>
                {txHash && (
                  <a
                    href={explorer('tx', txHash)}
                    target="_blank"
                    rel="noreferrer"
                    className="button button-secondary text-xs mt-2"
                  >
                    <span>VIEW TX ↗</span>
                  </a>
                )}
              </div>
            )}

            {txState === 'failed' && (
              <div className="tx-error-card mt-4">
                <AlertCircle size={20} className="text-red-500" />
                <p className="text-xs text-red-600">{errorMsg || 'Claim transaction failed.'}</p>
                <button
                  type="button"
                  className="button button-secondary text-xs mt-2"
                  onClick={executeClaim}
                >
                  RETRY
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
